# Base configuration for ImageNet training
# Shared defaults across all experiments

# Data settings
data_root: /fsx/imagenet
num_workers: 8
pin_memory: true
persistent_workers: true

# Model settings
model_name: resnet50
pretrained: false
num_classes: 1000

# Image preprocessing
img_size: 224
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# Training hyperparameters
batch_size: 256
epochs: 90
optimizer: sgd
lr: 0.1
momentum: 0.9
weight_decay: 1e-4
lr_scheduler: cosine
warmup_epochs: 5

# Mixed precision
precision: 16-mixed

# Logging
log_every_n_steps: 50
val_check_interval: 1.0

# Checkpointing
save_top_k: 3
monitor: val/acc1
mode: max

# Distributed training
strategy: ddp
sync_batchnorm: true

# Augmentation
random_crop: true
random_horizontal_flip: true
auto_augment: null  # options: null, 'imagenet', 'randaugment'
mixup_alpha: 0.0
cutmix_alpha: 0.0
label_smoothing: 0.0

# Misc
seed: 42
deterministic: false
