# LR Test: 0.01 (Extremely Conservative)
# Testing baseline low LR

data_root: /mnt/nvme_data/imagenet_subset
img_size: 224

batch_size: 256
num_workers: 8
pin_memory: true
persistent_workers: true
prefetch_factor: 2

model_name: resnet50
pretrained: false
num_classes: 100
compile_model: false

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# TEST: Extremely low LR
epochs: 20
optimizer: sgd
lr: 0.01  # Baseline low LR
momentum: 0.9
weight_decay: 0.00002
lr_scheduler: cosine
warmup_epochs: 2
max_epochs: 20

precision: 16-mixed

random_crop: true
random_horizontal_flip: true
auto_augment: null
mixup_alpha: 0.0
cutmix_alpha: 0.0
label_smoothing: 0.1

use_ema: false
gradient_clip_val: null

log_every_n_steps: 20
val_check_interval: 1.0

save_top_k: 3
monitor: val/acc1
mode: max

devices: 1
strategy: auto
sync_batchnorm: false

seed: 42
deterministic: false
