# ResNet Strikes Back (A2) Training Recipe
# Based on: https://arxiv.org/abs/2110.00476
# Target: ~80.4% top-1 accuracy on ImageNet with ResNet-50

# Data settings
data_root: /mnt/imagenet-data/imagenet  # Mounted EBS volume with ImageNet data
img_size: 224
batch_size: 384  # Per GPU (8 GPUs = 3072 effective batch)
num_workers: 32  # Per GPU (8 GPUs * 32 = 256 workers)
pin_memory: true
persistent_workers: true
prefetch_factor: 6  # Very aggressive prefetching to saturate GPUs

# Model settings
model_name: resnet50
pretrained: false
num_classes: 1000
compile_model: true  # PyTorch 2.0+ compilation for speed

# Image preprocessing (ImageNet standard)
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# Training hyperparameters (ResNet Strikes Back A2 recipe)
epochs: 600  # Extended training (A2 uses 600 epochs)
optimizer: sgd
lr: 6.0  # LR finder: 0.5 for 1 GPU @ batch 256, scaled: 0.5 * 8 * (384/256) = 6.0
momentum: 0.9
weight_decay: 0.0001  # Standard for from-scratch training (1e-4)
lr_scheduler: cosine
warmup_epochs: 5  # Standard warmup (ResNet Strikes Back A2)
max_epochs: 600  # Total training epochs
cosine_t_max: 100  # Fast decay over 100 epochs
eta_min: 1.0e-6  # Minimum LR (never reach exactly 0)

# Mixed precision training
precision: 16-mixed  # Faster training with minimal accuracy loss

# Augmentation (ResNet Strikes Back recipe)
random_crop: true
random_horizontal_flip: true
auto_augment: null  # No AutoAugment in base recipe
mixup_alpha: 0.2  # Mixup (ResNet Strikes Back A2)
cutmix_alpha: 1.0  # CutMix (ResNet Strikes Back A2)
label_smoothing: 0.1  # Label smoothing (ResNet Strikes Back A2)

# Regularization
use_ema: false  # Not used in base ResNet Strikes Back
gradient_clip_val: null

# Logging
log_every_n_steps: 100
val_check_interval: 1.0  # Validate every epoch

# Checkpointing
save_top_k: 5
monitor: val/acc1
mode: max

# Distributed training (for multi-GPU/multi-node)
devices: 8  # 8x A100 40GB GPUs
num_nodes: 1
strategy: ddp
sync_batchnorm: true

# Reproducibility
seed: 42
deterministic: false  # Set to true for reproducibility (slower)

# Notes:
# - This is the A2 recipe from ResNet Strikes Back
# - Expected accuracy: ~80.4% top-1 on ImageNet
# - Training time: ~600 epochs (longer than standard 90)
# - For faster training, use 90-100 epochs with slightly lower accuracy (~78-79%)
# - LR scaling: If using larger batch size, scale LR linearly
#   Example: batch_size=512 -> lr=1.0, batch_size=1024 -> lr=2.0
