# Tiny ImageNet configuration for smoke tests
# Uses logical subsetting - no need to create separate directory
# Overrides base.yaml for quick validation

# Data settings
data_root: /data2/imagenet  # Use full dataset
img_size: 224  # Keep standard size
batch_size: 32  # Small batch for CPU/testing
num_workers: 2  # Minimal workers for CPU

# Logical subsetting (no physical subset needed)
max_classes: 5              # Only use 5 classes
max_samples_per_class: 50   # Only 50 training samples per class
subset_seed: 42             # Reproducible subset selection

# Model settings
num_classes: 5  # Match max_classes

# Training settings
epochs: 1  # Just 1 epoch for smoke test
lr: 0.01
momentum: 0.9
weight_decay: 0.0001  # 1e-4
warmup_epochs: 0  # No warmup for quick test
max_epochs: 1  # Needed for LR scheduler

# Hardware settings (CPU-only for this test)
accelerator: cpu
devices: 1
strategy: auto
precision: 32
sync_batchnorm: false

# Validation
val_check_interval: 0.5

# Logging
log_every_n_steps: 5  # Log more frequently for tiny dataset

# Checkpointing
save_top_k: 1
